name: auto-sync-test-for-github-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout work repo
        uses: actions/checkout@v3
      - name: Set git token
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://${{secrets.credentials_github}}@github.com
      - name: Set git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<xiaojunnuo@qq.com>"
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install trident-sync
        run: |
          python -m pip install --upgrade pip
          pip install trident-sync
      - name: Trident sync execute
        run: |
          trident init
          trident remote --url=https://github.com/handsfree-test/sync-work-repo
          trident sync

